# Generated by Django 4.2.30 on 2026-05-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('total_pages', models.PositiveIntegerField(verbose_name='Всего страниц')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID из OpenLibrary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('pages_read', models.PositiveIntegerField(verbose_name='Прочитано страниц')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reader.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Сессия чтения',
                'verbose_name_plural': 'Сессии чтения',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('daily_target', models.PositiveIntegerField(verbose_name='Страниц в день')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reader.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'План чтения',
                'verbose_name_plural': 'Планы чтения',
            },
        ),
    ]
