# Generated by Django 4.2.30 on 2026-05-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего страниц'),
        ),
    ]
